// Frases do grupo: anime (figuras colecionáveis + camisetas geek/anime)

export const PHRASES_ANIME: Record<string, string[]> = {

  // ── Figura / Action Figure / Boneco Colecionável ──────────────────────────
  'figura anime': [
    'PRA QUEM TEM PRATELEIRA E ORGULHO DE MOSTRAR 🏆',
    'FIGURA QUE TODO FÃ DE VERDADE PRECISA TER 🎌',
    'PRA QUEM AMA O ANIME DE UM JEITO QUE A FAMÍLIA NÃO ENTENDE 😂',
    'COLECIONÁVEL QUE VOCÊ COMPRA E JÁ NÃO CONSEGUE PARAR 💎',
    'PRA DECORAR A PRATELEIRA E PROVAR QUE É FÃ SÉRIO 😎',
    'FIGURA DE PVC QUE VALE MAIS QUE QUALQUER ENFEITE COMUM 🌟',
    'PRA QUEM ASSISTE O ANIME E QUER O PERSONAGEM EM CASA 🎌',
    'PRESENTE PRA QUEM É OTAKU DE VERDADE — E SABE DISSO 🎁',
    'FIGURA QUE FAZ A PRATELEIRA PARECER DE LOJA ESPECIALIZADA 🏪',
    'PRA QUEM COLECIONA PORQUE AMA — E NÃO PARA 🔥',
    'ACTION FIGURE QUE FAZ TODO MUNDO PERGUNTAR QUAL ANIME É 👀',
    'PRA QUEM JÁ TEM A FIGURA MAS QUER MAIS UMA — É SEMPRE ASSIM 😅',
    'PERSONAGEM FAVORITO EM MINIATURA DE PERFEIÇÃO 💫',
    'PRA OTAKU, GEEK OU COLECIONADOR — ISSO AQUI É SÉRIO 🎌',
    'PVC DE QUALIDADE, PINTURA DETALHADA E PREÇO QUE FEZ SENTIDO AGORA 💰',
    'CADA FIGURA É UMA MEMÓRIA DO ARCO QUE MARCOU PRA SEMPRE ✨',
    'PRA QUEM COMPRA A FIGURA ANTES DE TERMINAR O ANIME 😂',
    'DETALHE PERFEITO DE QUEM ENTENDE QUE FANDOM É CULTURA 🎭',
    'ESSA FIGURA NÃO É ENFEITE — É DECLARAÇÃO DE FÃ 🗣️',
    'PRA COMPLETAR A COLEÇÃO QUE NUNCA TERMINA 🌟',
  ],

  // ── Funko Pop (colecionáveis de vinil) ────────────────────────────────────
  'funko pop': [
    'COLECIONÁVEL QUE O FÃ NÃO CONSEGUE TER SÓ UM 🎭',
    'PRA QUEM AMA O PERSONAGEM E PRECISA TER EM MINIATURA 😏',
    'FUNKO QUE VAI DIRETO PRA PRATELEIRA DE HONRA 🌟',
    'PRA QUEM COLECIONA MEMÓRIA EM VINIL 💎',
    'PRA QUEM GOSTA DE FANDOM DE VERDADE ✨',
    'FUNKO POP: O COLECIONÁVEL QUE ENCAIXOU NA ESTANTE E NO CORAÇÃO ❤️',
    'PRA QUEM TEM UMA PRATELEIRA DE FUNKO E JÁ NÃO TEM MAIS ESPAÇO — MAS COMPRA 😂',
    'PRA PRESENTEAR QUEM TEM FANDOM E NÃO SABE O QUE DAR 🎁',
    'VINIL QUE VALE MAIS DO QUE O PREÇO 💡',
    'PRA QUEM COLECIONA PERSONAGEM QUE MARCOU A VIDA 🔥',
    'FUNKO EXCLUSIVO: O TIPO QUE VOCÊ VÊ E COMPRA ANTES DE PENSAR 💸',
    'O CABEÇUDA QUE TODO FÃ QUER NA PRATELEIRA 👁️',
    'DE ANIME A MARVEL, DE SÉRIE A FILME — FUNKO COBRE TUDO 🎬',
  ],

  // ── Nendoroid / Figma / Figuarts (figuras articuladas premium) ────────────
  'nendoroid': [
    'O NENDOROID QUE TODO OTAKU COLOCOU NA LISTA HÁ MUITO TEMPO 🎌',
    'PRA QUEM SABE A DIFERENÇA ENTRE FIGURA BOA E FIGURA ÓTIMA 💎',
    'GOOD SMILE COMPANY: QUANDO A QUALIDADE É INEGOCIÁVEL 🏆',
    'NENDOROID QUE FICA NO SETUP E NINGUÉM PARA DE OLHAR 👀',
    'PRA QUEM QUER A MELHOR FIGURA DO PERSONAGEM — E SÓ ACEITA A MELHOR 🌟',
    'ARTICULADO, DETALHADO E COMPLETAMENTE IRRESISTÍVEL 💡',
    'PRESENTE QUE TODO OTAKU OLHA E SABE EXATAMENTE O VALOR 🎁',
    'PRA QUEM LEVA COLEÇÃO A SÉRIO E NÃO ACEITA MENOS DO QUE O ORIGINAL 🔥',
  ],

  // ── Camiseta Anime / Geek / Super-herói ───────────────────────────────────
  'camiseta anime': [
    'VESTIU O ANIME E JÁ DEU MATCH COM CADA FÃ NA RUA 👕',
    'PRA QUEM TEM ESTAMPA E TEM POSIÇÃO 🎌',
    'ESSA CAMISETA FALA MAIS DO QUE QUALQUER BIO DE PERFIL ✨',
    'PRA QUEM NÃO PRECISA EXPLICAR PRA OUTRO FÃ — ELE JÁ ENTENDEU 😏',
    'CAMISETA QUE FILTRA AS AMIZADES NA RUA 😂',
    'PRA QUEM LEVA FANDOM A SÉRIO — ATÉ NO LOOK 💪',
    'VESTIU, COLETOR DE ELOGIO DE FÃ ATIVADO 🌟',
    'PRA OTAKU QUE NÃO ESCONDE O QUE AMA 🎌',
    'ESSA ESTAMPA É DECLARAÇÃO DE FÃDOM 🔥',
    'PRA QUEM QUER SER RECONHECIDO PELA TURMA CERTA 👀',
    'HERÓI, VILÃO OU PERSONAGEM FAVORITO — AGORA NO SEU PEITO 💥',
    'PRA QUEM COMBINA GUARDA-ROUPA COM LISTA DE ANIMES 😎',
    'CAMISETA QUE NÃO É BÁSICA — É CULTURA 🎭',
    'PRA GEEK, NERD OU FÃ DE CARTEIRINHA 💎',
    'QUANDO A MODA ENCONTRA O FANDOM — E AMBOS SAEM GANHANDO 🌟',
    'PRA QUEM QUER QUE O LOOK CONTE A HISTÓRIA SEM ABRIR A BOCA 😌',
    'ESTAMPA QUE TODO MUNDO DO GRUPO RECONHECE DE LONGE 🏆',
    'PRA QUEM USA CAMISETA COM INTENÇÃO 🎯',
  ],

};
