// Auto-gerado por splitPhrases.mjs — NÃO editar manualmente
// Frases do grupo: automotivo

export const PHRASES_AUTOMOTIVO: Record<string, string[]> = {
  'tapete automotivo': [
    'CHÃO DO CARRO LIMPO QUE NINGUÉM VÊ MAS TODO MUNDO SENTE 🚗',
    'TAPETE QUE PROTEGE O ASSOALHO ✅',
    'PRA QUEM CUIDA DO CARRO ATÉ NO INTERIOR 💡',
    'TAPETE QUE CABE CERTO E FAZ DIFERENÇA 🌟',
    'PRA QUEM GOSTA DE CARRO IMPECÁVEL 💰',
  ],
  'capa de banco': [
    'BANCO PROTEGIDO DE QUALQUER COISA QUE APARECER 🚗',
    'PRA QUEM TEM PET, CRIANÇA OU OS DOIS 😤',
    'CAPA QUE COBRE E QUE LAVA FÁCIL ✅',
    'PRA QUEM CUIDA DO INTERIOR DO CARRO 💡',
    'PROTEÇÃO QUE SE PAGA NA PRIMEIRA BAGUNÇA 🌟',
  ],
  'lixeira automotiva': [
    'CARRO LIMPO COMEÇA PELA LIXEIRA 🚗',
    'PRA QUEM NÃO SUPORTA LIXO SOLTO NO CARRO 😤',
    'LIXEIRA QUE CABE EM QUALQUER LUGAR DO CARRO ✅',
    'PEQUENA, MAS FAZ GRANDE DIFERENÇA 💡',
    'PRA CARRO ORGANIZADO E LIMPO 🌟',
  ],
  'aromatizador automotivo': [
    'CARRO QUE CHEIRA BEM MUDA A VIBE DA VIAGEM 🚗',
    'PRA QUEM NÃO AGUENTA CHEIRO DE CARRO FECHADO 😤',
    'AROMATIZADOR QUE DURA E QUE CHEIRA DE VERDADE ✅',
    'PRA MOTORISTA QUE GOSTA DE AMBIENTE BOM 💡',
    'PEQUENO DETALHE, GRANDE DIFERENÇA 🌟',
  ],
  'rastreador veicular': [
    'PRA SABER ONDE O CARRO TÁ EM QUALQUER MOMENTO 🛡️',
    'SEGURANÇA QUE TODO CARRO MERECE ✅',
    'RASTREADOR QUE DÁ PAZ DE ESPÍRITO 💡',
    'PRA QUEM LEVA SEGURANÇA DO VEÍCULO A SÉRIO 🌟',
    'PROTEÇÃO QUE SE PAGA NA PRIMEIRA VEZ QUE PRECISAR 💰',
  ],
  'modulador bluetooth': [
    'MÚSICA DO CELULAR NO CARRO QUE NÃO TEM BLUETOOTH 🎵',
    'PRA QUEM QUER CONECTIVIDADE SEM TROCAR DE CARRO 💡',
    'MODULADOR QUE CONECTA RÁPIDO E FAZ FUNCIONAR ✅',
    'PRA DIRIGIR COM A PLAYLIST CERTA SEMPRE 🌟',
    'BARATO PRA CONECTAR O QUE PRECISAVA 💰',
  ],
  'carregador veicular': [
    'CHEGA EM CASA COM O CELULAR CARREGADO ⚡',
    'PRA QUEM NÃO CHEGA MORTO DE BATERIA 💡',
    'CARREGADOR QUE CARREGA DE VERDADE EM MOVIMENTO ✅',
    'PRA QUEM PASSA HORAS NO CARRO 🚗',
    'ESSENCIAL QUE TODO CARRO PRECISA 🌟',
  ],
  'cera automotiva': [
    'CARRO BRILHANDO QUE PARECE NOVO ✨',
    'PRA QUEM CUIDA DO CARRO COMO SE FOSSE DO ANO 💡',
    'CERA QUE PROTEGE E QUE BRILHA ✅',
    'PRA QUEM NÃO AGUENTA CARRO OPACO 😤',
    'CARRO TRATADO SEMPRE VALE MAIS 🌟',
  ],
  'palheta de limpador': [
    'PARA DE VER EM DIA DE CHUVA COM MÃO NA JANELA 🌧️',
    'PALHETA QUE LIMPA DE VERDADE SEM LISTAR ✅',
    'PRA QUEM DIRIGE CHUVA E PRECISA VER 💡',
    'PRA SEGURANÇA QUE COMEÇA NA VISIBILIDADE 🛡️',
    'TROCA RÁPIDA, RESULTADO IMEDIATO 🌟',
  ],
  'macaco hidráulico': [
    'PNEU FURADO? ELE TÁ LÁ 🔧',
    'MACACO QUE FAZ O SERVIÇO SEM ESFORÇO 💪',
    'PRA QUEM NÃO QUER DEPENDER DE SOCORRO NA ESTRADA ✅',
    'ESSENCIAL NO PORTA-MALAS DE QUEM VIAJA 💡',
    'SEGURANÇA EM QUALQUER RODOVIA 🌟',
  ],
  'compressor de ar': [
    'PNEU CALIBRADO SEM IR AO POSTO ⚡',
    'COMPRESSOR QUE FAZ O QUE PRECISA EM MINUTOS ✅',
    'PRA QUEM NÃO QUER DIRIGIR COM PNEU MURCHO 💡',
    'PRA QUEM CUIDA DO CARRO COM SERIEDADE 💪',
    'ESSENCIAL QUE TODO CARRO PRECISA 🌟',
  ],
  'extintor automotivo': [
    'EXIGÊNCIA QUE SALVA VIDA EM CASO DE EMERGÊNCIA 🚗',
    'PRA QUEM NÃO QUER DEPENDER DA SORTE 🛡️',
    'EXTINTOR QUE FAZ PARTE DA SEGURANÇA DO VEÍCULO ✅',
    'PRA QUEM LEVA SEGURANÇA VIÁRIA A SÉRIO 💡',
    'PRA TER E NUNCA PRECISAR (IDEALMENTE) 🌟',
  ],
};
