// Auto-gerado por splitPhrases.mjs — NÃO editar manualmente
// Frases do grupo: genericos

export const PHRASES_GENERICOS: Record<string, string[]> = {
  'tenis': [],
  'chinelo': [
    'ESSE CHINELO É LIBERDADE 🏖️',
    'PRA QUEM NÃO GOSTA DE PÉ PRESO 🌞',
    'CONFORTO DO PRIMEIRO AO ÚLTIMO PASSO 🦶',
    'PRA USAR NO DIA A DIA SEM CASTIGO 😌',
    'LEVE, FÁCIL, HONESTO ✅',
    'PRA QUEM ODEIA SAPATO FECHADO 😤',
    'PÉ FELIZ, DONO MAIS AINDA 💛',
    'CHINELO QUE DURA DE VERDADE 💪',
    'O ÚNICO CALÇADO QUE A MÃE USA E AINDA SERVE DE AMEAÇA 😂',
    'PRA IR NA PADARIA, NA PRAIA OU NO FIM DO MUNDO — CHINELO RESOLVE 🌍',
    'PÉ NO CHÃO, BOLSO NO AZUL, CONFORTO GARANTIDO 💰',
    'O BRASIL INTEIRO ENTENDE O QUE É CHINELO BOM 🇧🇷',
    'PRA QUEM PREFERE O CHÃO SEM INTERMEDIÁRIO 😌',
    'CALÇADO OFICIAL DO VERÃO QUE NUNCA PASSA 🌞',
    'PRA QUEM JÁ CANSOU DE AMARRAR CADARÇO 😅',
    'PRA PRAIA, PISCINA, MERCADO OU SOFÁ — SERVE PRA QUALQUER MISSÃO 🏖️',
    'O ÚNICO CALÇADO QUE VOCÊ PERDE E AINDA TEM O OUTRO 👀',
    'SIMPLES, LEVE E SEM ENROLAÇÃO — É ISSO QUE O PÉ PRECISA ⚡',
    'ESSE AQUI AGUENTA SOL, AREIA, ÁGUA E ATÉ A VIZINHA PEDINDO EMPRESTADO 😂',
    'PRA QUEM ANDA MUITO E NÃO QUER PAGAR COM DOR NO PÉ 🦶',
  ],
};
